# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :company do
    name "MyString"
    company_type "MyString"
    short_name "MyString"
    ur_zip_code "MyString"
    ur_city "MyString"
    ur_street "MyString"
    ur_house "MyString"
    ur_stroenie "MyString"
    ur_office "MyString"
    ur_post_equal "MyString"
    post_zip_code "MyString"
    post_city "MyString"
    post_street "MyString"
    post_house "MyString"
    post_stroenie "MyString"
    post_office "MyString"
    telephone "MyString"
    fax "MyString"
    email "MyString"
    inn 1
    kpp "MyString"
    ogrn "MyString"
    okpo "MyString"
    okved "MyString"
    ispolnitel "MyString"
    osnovanie_ispolnitel "MyString"
    bank_account "MyString"
    bank_corr_account "MyString"
    bank_name "MyString"
    bank_zip "MyString"
    bank_city "MyString"
    bank_street "MyString"
    bank_house "MyString"
    bank_stroenie "MyString"
    bank_office "MyString"
    bank_bik "MyString"
  end
end
