require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CouriersCompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # CouriersCompany. As you add validations to CouriersCompany, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CouriersCompaniesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all couriers_companies as @couriers_companies" do
      couriers_company = CouriersCompany.create! valid_attributes
      get :index, {}, valid_session
      assigns(:couriers_companies).should eq([couriers_company])
    end
  end

  describe "GET show" do
    it "assigns the requested couriers_company as @couriers_company" do
      couriers_company = CouriersCompany.create! valid_attributes
      get :show, {:id => couriers_company.to_param}, valid_session
      assigns(:couriers_company).should eq(couriers_company)
    end
  end

  describe "GET new" do
    it "assigns a new couriers_company as @couriers_company" do
      get :new, {}, valid_session
      assigns(:couriers_company).should be_a_new(CouriersCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested couriers_company as @couriers_company" do
      couriers_company = CouriersCompany.create! valid_attributes
      get :edit, {:id => couriers_company.to_param}, valid_session
      assigns(:couriers_company).should eq(couriers_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CouriersCompany" do
        expect {
          post :create, {:couriers_company => valid_attributes}, valid_session
        }.to change(CouriersCompany, :count).by(1)
      end

      it "assigns a newly created couriers_company as @couriers_company" do
        post :create, {:couriers_company => valid_attributes}, valid_session
        assigns(:couriers_company).should be_a(CouriersCompany)
        assigns(:couriers_company).should be_persisted
      end

      it "redirects to the created couriers_company" do
        post :create, {:couriers_company => valid_attributes}, valid_session
        response.should redirect_to(CouriersCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved couriers_company as @couriers_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        CouriersCompany.any_instance.stub(:save).and_return(false)
        post :create, {:couriers_company => {}}, valid_session
        assigns(:couriers_company).should be_a_new(CouriersCompany)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CouriersCompany.any_instance.stub(:save).and_return(false)
        post :create, {:couriers_company => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested couriers_company" do
        couriers_company = CouriersCompany.create! valid_attributes
        # Assuming there are no other couriers_companies in the database, this
        # specifies that the CouriersCompany created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CouriersCompany.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => couriers_company.to_param, :couriers_company => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested couriers_company as @couriers_company" do
        couriers_company = CouriersCompany.create! valid_attributes
        put :update, {:id => couriers_company.to_param, :couriers_company => valid_attributes}, valid_session
        assigns(:couriers_company).should eq(couriers_company)
      end

      it "redirects to the couriers_company" do
        couriers_company = CouriersCompany.create! valid_attributes
        put :update, {:id => couriers_company.to_param, :couriers_company => valid_attributes}, valid_session
        response.should redirect_to(couriers_company)
      end
    end

    describe "with invalid params" do
      it "assigns the couriers_company as @couriers_company" do
        couriers_company = CouriersCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CouriersCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => couriers_company.to_param, :couriers_company => {}}, valid_session
        assigns(:couriers_company).should eq(couriers_company)
      end

      it "re-renders the 'edit' template" do
        couriers_company = CouriersCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CouriersCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => couriers_company.to_param, :couriers_company => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested couriers_company" do
      couriers_company = CouriersCompany.create! valid_attributes
      expect {
        delete :destroy, {:id => couriers_company.to_param}, valid_session
      }.to change(CouriersCompany, :count).by(-1)
    end

    it "redirects to the couriers_companies list" do
      couriers_company = CouriersCompany.create! valid_attributes
      delete :destroy, {:id => couriers_company.to_param}, valid_session
      response.should redirect_to(couriers_companies_url)
    end
  end

end
