require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CouriersTasksController do

  # This should return the minimal set of attributes required to create a valid
  # CouriersTask. As you add validations to CouriersTask, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CouriersTasksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all couriers_tasks as @couriers_tasks" do
      couriers_task = CouriersTask.create! valid_attributes
      get :index, {}, valid_session
      assigns(:couriers_tasks).should eq([couriers_task])
    end
  end

  describe "GET show" do
    it "assigns the requested couriers_task as @couriers_task" do
      couriers_task = CouriersTask.create! valid_attributes
      get :show, {:id => couriers_task.to_param}, valid_session
      assigns(:couriers_task).should eq(couriers_task)
    end
  end

  describe "GET new" do
    it "assigns a new couriers_task as @couriers_task" do
      get :new, {}, valid_session
      assigns(:couriers_task).should be_a_new(CouriersTask)
    end
  end

  describe "GET edit" do
    it "assigns the requested couriers_task as @couriers_task" do
      couriers_task = CouriersTask.create! valid_attributes
      get :edit, {:id => couriers_task.to_param}, valid_session
      assigns(:couriers_task).should eq(couriers_task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CouriersTask" do
        expect {
          post :create, {:couriers_task => valid_attributes}, valid_session
        }.to change(CouriersTask, :count).by(1)
      end

      it "assigns a newly created couriers_task as @couriers_task" do
        post :create, {:couriers_task => valid_attributes}, valid_session
        assigns(:couriers_task).should be_a(CouriersTask)
        assigns(:couriers_task).should be_persisted
      end

      it "redirects to the created couriers_task" do
        post :create, {:couriers_task => valid_attributes}, valid_session
        response.should redirect_to(CouriersTask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved couriers_task as @couriers_task" do
        # Trigger the behavior that occurs when invalid params are submitted
        CouriersTask.any_instance.stub(:save).and_return(false)
        post :create, {:couriers_task => {}}, valid_session
        assigns(:couriers_task).should be_a_new(CouriersTask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CouriersTask.any_instance.stub(:save).and_return(false)
        post :create, {:couriers_task => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested couriers_task" do
        couriers_task = CouriersTask.create! valid_attributes
        # Assuming there are no other couriers_tasks in the database, this
        # specifies that the CouriersTask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CouriersTask.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => couriers_task.to_param, :couriers_task => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested couriers_task as @couriers_task" do
        couriers_task = CouriersTask.create! valid_attributes
        put :update, {:id => couriers_task.to_param, :couriers_task => valid_attributes}, valid_session
        assigns(:couriers_task).should eq(couriers_task)
      end

      it "redirects to the couriers_task" do
        couriers_task = CouriersTask.create! valid_attributes
        put :update, {:id => couriers_task.to_param, :couriers_task => valid_attributes}, valid_session
        response.should redirect_to(couriers_task)
      end
    end

    describe "with invalid params" do
      it "assigns the couriers_task as @couriers_task" do
        couriers_task = CouriersTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CouriersTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => couriers_task.to_param, :couriers_task => {}}, valid_session
        assigns(:couriers_task).should eq(couriers_task)
      end

      it "re-renders the 'edit' template" do
        couriers_task = CouriersTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CouriersTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => couriers_task.to_param, :couriers_task => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested couriers_task" do
      couriers_task = CouriersTask.create! valid_attributes
      expect {
        delete :destroy, {:id => couriers_task.to_param}, valid_session
      }.to change(CouriersTask, :count).by(-1)
    end

    it "redirects to the couriers_tasks list" do
      couriers_task = CouriersTask.create! valid_attributes
      delete :destroy, {:id => couriers_task.to_param}, valid_session
      response.should redirect_to(couriers_tasks_url)
    end
  end

end
