require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DocumentBeznalSchetsController do

  # This should return the minimal set of attributes required to create a valid
  # DocumentBeznalSchet. As you add validations to DocumentBeznalSchet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DocumentBeznalSchetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all document_beznal_schets as @document_beznal_schets" do
      document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:document_beznal_schets).should eq([document_beznal_schet])
    end
  end

  describe "GET show" do
    it "assigns the requested document_beznal_schet as @document_beznal_schet" do
      document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
      get :show, {:id => document_beznal_schet.to_param}, valid_session
      assigns(:document_beznal_schet).should eq(document_beznal_schet)
    end
  end

  describe "GET new" do
    it "assigns a new document_beznal_schet as @document_beznal_schet" do
      get :new, {}, valid_session
      assigns(:document_beznal_schet).should be_a_new(DocumentBeznalSchet)
    end
  end

  describe "GET edit" do
    it "assigns the requested document_beznal_schet as @document_beznal_schet" do
      document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
      get :edit, {:id => document_beznal_schet.to_param}, valid_session
      assigns(:document_beznal_schet).should eq(document_beznal_schet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DocumentBeznalSchet" do
        expect {
          post :create, {:document_beznal_schet => valid_attributes}, valid_session
        }.to change(DocumentBeznalSchet, :count).by(1)
      end

      it "assigns a newly created document_beznal_schet as @document_beznal_schet" do
        post :create, {:document_beznal_schet => valid_attributes}, valid_session
        assigns(:document_beznal_schet).should be_a(DocumentBeznalSchet)
        assigns(:document_beznal_schet).should be_persisted
      end

      it "redirects to the created document_beznal_schet" do
        post :create, {:document_beznal_schet => valid_attributes}, valid_session
        response.should redirect_to(DocumentBeznalSchet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved document_beznal_schet as @document_beznal_schet" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentBeznalSchet.any_instance.stub(:save).and_return(false)
        post :create, {:document_beznal_schet => {}}, valid_session
        assigns(:document_beznal_schet).should be_a_new(DocumentBeznalSchet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentBeznalSchet.any_instance.stub(:save).and_return(false)
        post :create, {:document_beznal_schet => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested document_beznal_schet" do
        document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
        # Assuming there are no other document_beznal_schets in the database, this
        # specifies that the DocumentBeznalSchet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DocumentBeznalSchet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => document_beznal_schet.to_param, :document_beznal_schet => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested document_beznal_schet as @document_beznal_schet" do
        document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
        put :update, {:id => document_beznal_schet.to_param, :document_beznal_schet => valid_attributes}, valid_session
        assigns(:document_beznal_schet).should eq(document_beznal_schet)
      end

      it "redirects to the document_beznal_schet" do
        document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
        put :update, {:id => document_beznal_schet.to_param, :document_beznal_schet => valid_attributes}, valid_session
        response.should redirect_to(document_beznal_schet)
      end
    end

    describe "with invalid params" do
      it "assigns the document_beznal_schet as @document_beznal_schet" do
        document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentBeznalSchet.any_instance.stub(:save).and_return(false)
        put :update, {:id => document_beznal_schet.to_param, :document_beznal_schet => {}}, valid_session
        assigns(:document_beznal_schet).should eq(document_beznal_schet)
      end

      it "re-renders the 'edit' template" do
        document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DocumentBeznalSchet.any_instance.stub(:save).and_return(false)
        put :update, {:id => document_beznal_schet.to_param, :document_beznal_schet => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested document_beznal_schet" do
      document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
      expect {
        delete :destroy, {:id => document_beznal_schet.to_param}, valid_session
      }.to change(DocumentBeznalSchet, :count).by(-1)
    end

    it "redirects to the document_beznal_schets list" do
      document_beznal_schet = DocumentBeznalSchet.create! valid_attributes
      delete :destroy, {:id => document_beznal_schet.to_param}, valid_session
      response.should redirect_to(document_beznal_schets_url)
    end
  end

end
